module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  collectCoverage: true,
  collectCoverageFrom: [
    './src/**/*.ts',
    '!./src/**/*.d.ts',
    '!./src/index.ts',
    '!./src/schedule.ts',
    '!./src/start.ts',
    '!./src/*consts/gameTypesArray.ts',
    '!./src/*utils/progressHandler.ts',
    '!./src/*utils/formatGameType.ts',
    '!./src/*utils/pipe.ts',
    '!./src/*utils/generateBasicFolders.ts',
    '!./src/*utils/generateBasicHTML.ts',
    '!./src/*utils/logger.ts',
    '!./src/*utils/request.ts',
    '!./src/*output/**/*.ts',
    '!./src/!prepareReplaysList/**/*.ts',
    '!./src/!yearStatistics/**/*.ts',
    '!./src/!tests/**/*.ts',
    '!./src/jobs/**/*.ts',
  ],
  automock: false,
  resetMocks: false,
  coverageReporters: ['clover', 'json', 'lcov'],
  coverageThreshold: {
    global: {
      lines: 100,
    },
  },
};
