/* eslint-disable max-lines */
import type { Linter } from 'eslint';

const unicornRules: Linter.RulesRecord = {
  'unicorn/better-regex': 2,
  'unicorn/catch-error-name': [2, { name: 'error', ignore: ['err'] }],
  'unicorn/consistent-assert': 0,
  'unicorn/consistent-date-clone': 2,
  'unicorn/consistent-destructuring': 2,
  'unicorn/consistent-empty-array-spread': 2,
  'unicorn/consistent-existence-index-check': 2,
  'unicorn/consistent-function-scoping': [2, { checkArrowFunctions: true }],
  'unicorn/custom-error-definition': 2,
  'unicorn/empty-brace-spaces': 2,
  'unicorn/error-message': 2,
  'unicorn/escape-case': 2,
  'unicorn/expiring-todo-comments': 0,
  'unicorn/explicit-length-check': [2, { 'non-zero': 'greater-than' }],
  'unicorn/filename-case': 0,
  'unicorn/import-style': 0,
  'unicorn/new-for-builtins': 2,
  'unicorn/no-abusive-eslint-disable': 2,
  'unicorn/no-accessor-recursion': 2,
  'unicorn/no-anonymous-default-export': 2,
  'unicorn/no-array-callback-reference': 0,
  'unicorn/no-array-for-each': 0,
  'unicorn/no-array-method-this-argument': 2,
  'unicorn/no-array-push-push': 2,
  'unicorn/no-array-reduce': 0,
  'unicorn/no-await-expression-member': 2,
  'unicorn/no-await-in-promise-methods': 2,
  'unicorn/no-console-spaces': 2,
  'unicorn/no-document-cookie': 2,
  'unicorn/no-empty-file': 2,
  'unicorn/no-for-loop': 2,
  'unicorn/no-hex-escape': 2,
  'unicorn/no-instanceof-builtins': 2,
  'unicorn/no-invalid-fetch-options': 2,
  'unicorn/no-invalid-remove-event-listener': 2,
  'unicorn/no-keyword-prefix': 0,
  'unicorn/no-length-as-slice-end': 2,
  'unicorn/no-lonely-if': 2,
  'unicorn/no-magic-array-flat-depth': 2,
  'unicorn/no-named-default': 2,
  'unicorn/no-negated-condition': 2,
  'unicorn/no-negation-in-equality-check': 2,
  'unicorn/no-nested-ternary': 2,
  'unicorn/no-new-array': 2,
  'unicorn/no-new-buffer': 2,
  'unicorn/no-null': 0,
  'unicorn/no-object-as-default-parameter': 2,
  'unicorn/no-process-exit': 2,
  'unicorn/no-single-promise-in-promise-methods': 2,
  'unicorn/no-static-only-class': 2,
  'unicorn/no-thenable': 2,
  'unicorn/no-this-assignment': 2,
  'unicorn/no-typeof-undefined': 2,
  'unicorn/no-unnecessary-await': 2,
  'unicorn/no-unnecessary-polyfills': 2,
  'unicorn/no-unreadable-array-destructuring': 2,
  'unicorn/no-unreadable-iife': 2,
  'unicorn/no-unused-properties': 2,
  'unicorn/no-useless-fallback-in-spread': 2,
  'unicorn/no-useless-length-check': 2,
  'unicorn/no-useless-promise-resolve-reject': 2,
  'unicorn/no-useless-spread': 2,
  /** Disabled because it's forbid such code:
    * case 1:
    * default: { ... }
    *
    * But because of ts/switch-exhaustiveness-check rule we must add all
    * possible cases handing in switch. Sometimes we want to combine default
    * and some cases which this rule is forbid to do */

  'unicorn/no-useless-switch-case': 0,
  'unicorn/no-useless-undefined': [
    2,
    {
      // In situations where function receive value or undefined this rule is
      // forbid to use undefined in function arguments
      // By undefined type I mean `val: string | undefined` type,
      // not `val?: string`. In the first case undefined is mandatory and must
      // be passed, while in the second case undefined can be removed
      checkArguments: false,
    },
  ],
  'unicorn/no-zero-fractions': 2,
  'unicorn/number-literal-case': 2,
  'unicorn/numeric-separators-style': 2,
  'unicorn/prefer-add-event-listener': 2,
  'unicorn/prefer-array-find': 2,
  'unicorn/prefer-array-flat': 2,
  'unicorn/prefer-array-flat-map': 2,
  'unicorn/prefer-array-index-of': 2,
  'unicorn/prefer-array-some': 2,
  'unicorn/prefer-at': 2,
  'unicorn/prefer-blob-reading-methods': 2,
  'unicorn/prefer-code-point': 2,
  'unicorn/prefer-date-now': 2,
  'unicorn/prefer-default-parameters': 2,
  'unicorn/prefer-dom-node-append': 2,
  'unicorn/prefer-dom-node-dataset': 2,
  'unicorn/prefer-dom-node-remove': 2,
  'unicorn/prefer-dom-node-text-content': 2,
  'unicorn/prefer-event-target': 2,
  'unicorn/prefer-export-from': 2,
  'unicorn/prefer-global-this': 2,
  'unicorn/prefer-includes': 2,
  'unicorn/prefer-json-parse-buffer': 2,
  'unicorn/prefer-keyboard-event-key': 2,
  'unicorn/prefer-logical-operator-over-ternary': 2,
  'unicorn/prefer-math-min-max': 2,
  'unicorn/prefer-math-trunc': 2,
  'unicorn/prefer-modern-dom-apis': 2,
  'unicorn/prefer-modern-math-apis': 2,
  'unicorn/prefer-module': 2,
  'unicorn/prefer-native-coercion-functions': 2,
  'unicorn/prefer-negative-index': 2,
  'unicorn/prefer-node-protocol': 2,
  'unicorn/prefer-number-properties': 2,
  'unicorn/prefer-object-from-entries': 2,
  'unicorn/prefer-optional-catch-binding': 2,
  'unicorn/prefer-prototype-methods': 2,
  'unicorn/prefer-query-selector': 2,
  'unicorn/prefer-reflect-apply': 2,
  'unicorn/prefer-regexp-test': 2,
  'unicorn/prefer-set-has': 2,
  'unicorn/prefer-set-size': 2,
  'unicorn/prefer-spread': 1,
  'unicorn/prefer-string-raw': 2,
  'unicorn/prefer-string-replace-all': 2,
  'unicorn/prefer-string-slice': 2,
  'unicorn/prefer-string-starts-ends-with': 2,
  'unicorn/prefer-string-trim-start-end': 2,
  'unicorn/prefer-structured-clone': 2,
  'unicorn/prefer-switch': 2,
  'unicorn/prefer-ternary': 2,
  'unicorn/prefer-top-level-await': 2,
  'unicorn/prefer-type-error': 2,
  'unicorn/prevent-abbreviations': [
    2,
    {
      allowList: {
        prop: true,
        Prop: true,
        props: true,
        Props: true,
        ref: true,
        Ref: true,
        env: true,
        Env: true,
        param: true,
        Param: true,
        params: true,
        Params: true,
      },
    },
  ],
  'unicorn/relative-url-style': 2,
  'unicorn/require-array-join-separator': 2,
  'unicorn/require-number-to-fixed-digits-argument': 2,
  'unicorn/require-post-message-target-origin': 2,
  'unicorn/string-content': 2,
  'unicorn/switch-case-braces': 2,
  'unicorn/template-indent': 2,
  'unicorn/text-encoding-identifier-case': 2,
  'unicorn/throw-new-error': [2],
};

export default unicornRules;
